### ISSUE TITLE
Future task: Log System

### ISSUE THREAD

**Issue by NaseemSrour** [NaseemSrour/Deliveries#18]
We need logs, for database's executed queries and results for example.
Not just simple prints as it is now.

Not just for the DB, a generic logger that can be used anywhere; server requests, responses to client, ... etc.

Rudy suggested looking into this:
https://docs.python.org/3/howto/logging.html

**Comment by rudyeila** [comment]
I'll do this

**Comment by rudyeila** [comment]
Please review.
