### ISSUE TITLE
Handle HTTP Requests for Item

### ISSUE THREAD

**Issue by NaseemSrour** [NaseemSrour/Deliveries#21]
Handle the HTTP requests for Item in server.py, which will use the DB functionality in DBItem class.
Whoever takes this task (Naseem'll probably handle it) should discuss here first what'll GET, POST, PUT and all others will do, before implementing.

**Comment by rudyeila** [comment]
Will take a lot later and post my thoughts on the methods.

**Comment by NaseemSrour** [comment]
Sure!
I haven't looked into it yet, this week was a busy one as you surely know.
